### ISSUE TITLE
Торжественное открытие лабы

### ISSUE THREAD

**Issue by MrGreenball** [cyblabs/xlab#7]
- [x] Установить дверь
- [x] Подключить теплый пол в туалет и в лабу
- [x] Перенести трубу
- [x] Повесить держатели инструментов 
- [ ] Пересобрать CNC 
- [x] Залить бабло
- [x] Пригласить друзей
- [x] Подгтовить к запуску фармбот

**Comment by xhipster** [comment]
Postponed until better times. It needs so much of work:
- external such as remove the garbage and ugly walls
- internal such more clean and ordered space, finalization of key projects
- in-house such reconstruction of infrastructure space

Also before 'opening', it must become sustainable and start to provide public services
